sudo: false
language: cpp
notifications:
  email: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="10"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm install
  - ssh -V
script: npm test
